---
- name: Install git and download repository
  hosts: all
  become: yes
  tasks:
    - name: download git into servers
      apt:
        name: git
        state: present
        update_cache: yes
    - name: clone a repo from github
      git:
        repo: https://github.com/IntelliqDevops/maven.git
        dest: /tmp/mygit
    - name: create a user
      user:
        name: rani
        password: intelliqit
    - name: change ownership and group ownership of the folder where git downloaded
      file:
        name: /tmp/mygit
        owner: rani
        group: rani
...
